name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build for UI
      run: docker run --rm -it -v $PWD/console:/app -w /app starwhaleai/nodejs:0.1.0-nightly-20220505190936 yarn install;docker run --rm -it -v $PWD/console:/app -w /app starwhaleai/nodejs:0.1.0-nightly-20220505190936 yarn build
    - name: Build By maven
      run: 	docker run --rm -it -v $PWD/server:/app -w /app maven:3.8.5-openjdk-11 mvn clean package -DskipTests
    - name: Build Controller
      run: docker build -f docker/Dockerfile.controller -t starwhaleai/controller:0.1.0-nightly-$(date +%s)
    - name: Build Agent
      run: docker build -f docker/Dockerfile.agent -t starwhaleai/agent:0.1.0-nightly-$(date +%s)
