name: Release by Tag CI

on:
  push:
    tags:
      - 'v*.*.*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      # UI build
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
          cache-dependency-path: "./console/yarn.lock"

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Install yarn
        working-directory: ./console
        run: make install-yarn

      - uses: actions/cache@v3
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: |
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
            **/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install project dependencies
        working-directory: ./console
        if: steps.yarn-cache.outputs.cache-hit != 'true' # Over here!
        run: make install-dependencies

      - name: Yarn Build
        working-directory: ./console
        run: make build-ui

      # jar build
      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: 'maven'
          server-id: starwhale # Value of the distributionManagement/repository/id field of the pom.xml
      - name: Build with Maven
        working-directory: ./server
        run: make build-package

      # docker-hub login
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1
        with:
          # Optionally strip `v` prefix
          strip_v: true
      # docker image build
      - name: Docker image build and push
        working-directory: ./docker
        env:
          RELEASE_VERSION: v${{ steps.tag.outputs.tag }}
        run: |
          make build-base VERSION_FORMAT=$RELEASE_VERSION
          make build-starwhale VERSION_FORMAT=$RELEASE_VERSION
          make build-taskset VERSION_FORMAT=$RELEASE_VERSION
          make build-server-when-ui-and-jar-built VERSION_FORMAT=$RELEASE_VERSION
          make release
      # todo cli build and upload
